<script setup lang="ts">
import { tab } from "@/main";
import { tmp, player } from "@/main";
import { format } from "@/format";
import Game_ColResearches from "./Game_ColResearches/Game_ColResearches.vue";
</script>
<template>
    <div id="colosseum" v-if="tab.currentTab === 5">
        <!-- <div class="flex-container" style="flex-direction: row; justify-content: center; font-size: 1.4vw; margin-bottom: 1vw;" v-if="Decimal.gte(timesCompleted('nk'), 1)"> 
            <button @click="switchSubTab(0, 0)" style="color: #f40" class="normalTabButton smallColBorder colButton fontVerdana"> 
                Challenges
            </button> 
            <button @click="switchSubTab(1, 0)" style="color: #f40" class="normalTabButton smallColBorder colButton fontVerdana" > 
                Research
            </button>
        </div> -->
        <div class="flex-container fontVerdana" style="flex-direction: column; justify-content: center; margin-bottom: 1vw">
            <span style="color: #f40; text-align: center; font-size: 0.7vw">
                Colosseum Power is being generated by the current amount of your Kuaraniai, but decaying over time.
            </span>
            <span style="color: #f40; text-align: center; font-size: 1.2vw">
                You have 
                <span style="font-size: 1.4vw"><b>{{ format(player.gameProgress.col.power, 2) }}</b></span> 
                Colosseum Power. 
                <span style="font-size: 1vw">({{ format(tmp.col.truePowGen, 2) }}/s)</span>
            </span>
            <!-- <span style="text-align: center; font-size: 1.2vw" :style="{ color: player.gameProgress.col.completedAll ? '#0080FF' : '#FF4000' }">
                This will give you about 
                <span style="font-size: 1.4vw"><b>{{ formatTime(player.gameProgress.col.maxTime, 3) }}</b></span>
                within challenges.
            </span> -->
            <span v-if="tab.tabList[tab.currentTab][0] === 0" class="whiteText" style="font-size: 0.65vw; text-align: center; margin-top: 0.5vw">
                If you feel stuck, you can get achievements! Some achievement rewards don't reset on Colosseum resets!
            </span>
            <!-- <span v-if="Decimal.gte(timesCompleted('su'), 1) && tab.tabList[tab.currentTab][0] === 0" class="whiteText" style="font-size: 0.65vw; text-align: center; margin-top: 0.5vw">
                You may change the difficulty to get achievements, or other challenges may force you into certain difficulties! Changing the difficulty will not change the rewards you already have.
            </span> -->
        </div>
        <!-- <div class="flex-container" style="flex-direction: row; justify-content: center; margin-top: 1.2vw" v-if="tab.tabList[tab.currentTab][0] === 0">
            <Game_ColChallenges />
        </div> -->
        <div style="background-color: #410; border: 0.2vw solid #ff4000; margin-left: auto; margin-right: auto; display: flex; justify-content: center; flex-direction: row; box-shadow: 0 0 0.8vw 0.24vw rgb(66, 17, 0); height: 40vw; width: 80vw;" v-if="tab.tabList[tab.currentTab][0] === 1">
            <Game_ColResearches />
        </div>
    </div>
</template>
